"""Shared global constants package."""

from .gameplay_constants import VOICE_MAP, VOICE_ORDER
from .runtime_constants import (
    DEFAULT_BILIBILI_MID,
    INFRASTRUCTURE_ROOM,
    INFRASTRUCTURE_SKILL_SUFFIX,
    POTENTIAL_SUFFIX,
    TRUST_ATTRIBUTE_LABELS,
)
from .wiki_constants import (
    ACQUISITION_METHOD,
    INFRASTRUCTURE_CONDITION,
    MAPPING_SKILL_TYPE,
    POSITION,
    PROFESSION,
    SKILL_TRIGGER_TYPE,
    SKILL_TYPE,
)

__all__ = [
    "ACQUISITION_METHOD",
    "PROFESSION",
    "POSITION",
    "SKILL_TYPE",
    "SKILL_TRIGGER_TYPE",
    "MAPPING_SKILL_TYPE",
    "VOICE_ORDER",
    "INFRASTRUCTURE_CONDITION",
    "VOICE_MAP",
    "POTENTIAL_SUFFIX",
    "INFRASTRUCTURE_ROOM",
    "DEFAULT_BILIBILI_MID",
    "TRUST_ATTRIBUTE_LABELS",
    "INFRASTRUCTURE_SKILL_SUFFIX",
]
